name: Deploy Clone Bot to Heroku via Github Workflows (EU Region)

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 8c6cf6de-35ff-410d-94e7-dd6c92bc7ece
          heroku_app_name: driveclonebot1234
          heroku_email: julianpsotka@gmail.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_telegram_token: ${{secrets.telegram_token}}
          HD_user_ids: ${{secrets.user_ids}}
          HD_group_ids: ${{secrets.group_ids}}
